name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: brew install nasm x86_64-elf-gcc x86_64-elf-binutils
      
    - name: make
      run: make 
      run: mv output/os-image.bin os-image.bin
      run: make
      run: comm output/os-image.bin os-image.bin > diff.txt

